### ISSUE TITLE
常用组件的 docker-compose.yaml

### ISSUE THREAD

**Issue by yahuian** [yahuian/blog#22]
## MySQL

```yaml
mysql:
  image: mysql:8.0.33
  ports:
    - "3306:3306"
  restart: always
  environment:
    TZ: Asia/Shanghai
    MYSQL_DATABASE: "${database_name}"
    MYSQL_ROOT_PASSWORD: "${password}"
  volumes:
    - "/data/mysql:/var/lib/mysql"
  command:
    [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'
    ]
```
